///! Commands for compiling rust code for `Android`,
///! generation/aligning/signing/installing/starting on device APKs and AAB,
///! generation `AndroidManifest.xml` and so on.
mod add_libs_into_aapt2;
mod add_libs_into_apk;
mod align_apk;
mod attach_logger;
mod build_apks;
mod detect_abi;
mod extract_apk;
mod gen_aab_from_modules;
mod gen_aab_key;
mod gen_debug_key;
mod gen_manifest;
mod gen_unaligned_apk;
mod gen_zip_modules;
mod install_apk;
mod jarsigner;
mod read_manifest;
mod remove_content;
mod rust_compile;
mod rust_compile_macroquad;
mod save_manifest;
mod sign_apk;
mod start_apk;
mod write_zip;

pub use add_libs_into_aapt2::*;
pub use add_libs_into_apk::*;
pub use align_apk::*;
pub use attach_logger::*;
pub use build_apks::*;
pub use detect_abi::*;
pub use extract_apk::*;
pub use gen_aab_from_modules::*;
pub use gen_aab_key::*;
pub use gen_debug_key::*;
pub use gen_manifest::*;
pub use gen_unaligned_apk::*;
pub use gen_zip_modules::*;
pub use install_apk::*;
pub use jarsigner::*;
pub use read_manifest::*;
pub use remove_content::*;
pub use rust_compile::*;
pub use rust_compile_macroquad::*;
pub use save_manifest::*;
pub use sign_apk::*;
pub use start_apk::*;
pub use write_zip::*;
