/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_startup_hip_RustCode */

#ifndef _Included_com_startup_hip_RustCode
#define _Included_com_startup_hip_RustCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_startup_hip_RustCode
 * Method:    doStuff
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_startup_hip_RustCode_doStuff
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
