rust = "1.97.1"
android_command_line_tools = "15859902"
android_api_level = "36"
android_min_sdk = "23"
android_build_tools = "36.0.0"
android_ndk = "28.2.13676358"
android_gradle_plugin = "9.3.1"
androidx_appcompat = "1.8.0"
androidx_fragment = "1.9.0"
play_billing = "9.1.0"
play_games_services = "21.0.0"
play_app_update = "2.1.0"
google_mobile_ads = "25.0.0"
user_messaging_platform = "4.0.0"
bundletool = "1.18.3"
gradle = "9.5.0"
java_runtime = "17"
java_bytecode = "17"
