rust = "1.97.1"
android_command_line_tools = "15859902"
android_api_level = "31"
android_build_tools = "30.0.3"
android_ndk = "27.3.13750724"
bundletool = "1.18.3"
gradle = "7.4"
java_runtime = "17"
java_bytecode = "11"
