[package]
name = "crossbow-ios"
version = "0.2.3"
edition.workspace = true
authors = ["DodoRare Team <support@dodorare.com>"]
description = "Cross-Platform build tools and toolkit for games"
repository = "https://github.com/dodorare/crossbow"
license = "MIT OR Apache-2.0"
keywords = ["crossbow", "ios", "port"]
readme = "README.md"
build = "build.rs"

[dependencies]
thiserror = { workspace = true }
displaydoc = { workspace = true }
anyhow = { workspace = true }

objc2 = { workspace = true }
block2 = { workspace = true }

[features]
default = [
    "eventkit",
    "avfoundation",
    "photos",
    "addressbook",
    "mediaplayer",
    "coremotion",
    "speech",
    "corelocation"
]
eventkit = []
avfoundation = []
photos = []
addressbook = []
mediaplayer = []
coremotion = []
speech = []
corelocation = []
