buildscript {
    apply from: "config.gradle"
    repositories {
        google()
        mavenCentral()
        mavenCrossbowGithub()

        // Crossbow custom plugins maven repositories
        String[] mavenRepos = getCrossbowPluginsMavenRepos()
        if (mavenRepos != null && mavenRepos.size() > 0) {
            for (String repoUrl : mavenRepos) {
                maven {
                    url repoUrl
                }
            }
        }
    }
    dependencies {
        classpath libraries.androidGradlePlugin
    }
}

apply plugin: "com.android.application"
apply from: "config.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
        mavenCrossbowGithub()

        // Crossbow custom plugins maven repositories
        String[] mavenRepos = getCrossbowPluginsMavenRepos()
        if (mavenRepos != null && mavenRepos.size() > 0) {
            for (String repoUrl : mavenRepos) {
                maven {
                    url repoUrl
                }
            }
        }
    }
}

dependencies {
    if (getCrossbowAndroidRuntime() == "game-activity") {
        implementation libraries.appcompat
        implementation libraries.gameActivity
    }

    if (getCrossbowBridge()) {
        if (rootProject.findProject(":lib")) {
            implementation project(":lib")
        } else if (rootProject.findProject(":crossbow:lib")) {
            implementation project(":crossbow:lib")
        } else if (getCustomBuildMode()) {
            // Custom build mode. In this scenario this project is the only one around and the Crossbow
            // library is available through the pre-generated crossbow-lib.*.aar android archive files.
            debugImplementation fileTree(dir: "../libs/debug", include: ["*.jar", "*.aar"])
            releaseImplementation fileTree(dir: "../libs/release", include: ["*.jar", "*.aar"])
        } else {
            implementation libraries.crossbowLibrary
        }
    }

    // Crossbow plugins remote dependencies
    String[] remoteDeps = getCrossbowPluginsRemoteBinaries()
    if (remoteDeps != null && remoteDeps.size() > 0) {
        for (String dep : remoteDeps) {
            implementation dep
        }
    }
    // Crossbow plugins local dependencies
    String[] pluginsBinaries = getCrossbowPluginsLocalBinaries()
    if (pluginsBinaries != null && pluginsBinaries.size() > 0) {
        implementation files(pluginsBinaries)
    }
    // Crossbow plugins local project dependencies
    String[] pluginsProjects = getCrossbowPluginsLocalProjects()
    if (pluginsProjects != null && pluginsProjects.size() > 0) {
        for (String dep : pluginsProjects) {
            implementation project(dep)
        }
    }
}

android {
    namespace = "com.crossbow.game"
    compileSdk = versions.compileSdk
    buildToolsVersion = versions.buildTools
    ndkVersion = versions.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(versions.javaVersion)
        targetCompatibility = JavaVersion.toVersion(versions.javaVersion)
    }

    androidResources {
        // Preserve Crossbow's hidden project assets in generated APKs and bundles.
        ignoreAssetsPattern = "!.svn:!.git:!.gitignore:!.ds_store:!*.scc:<dir>_*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    defaultConfig {
        // Feel free to modify the application id to your own.
        applicationId = getExportPackageName()
        versionCode = getExportVersionCode()
        versionName = getExportVersionName()
        minSdk = getExportMinSdkVersion()
        targetSdk = getExportTargetSdkVersion()

        missingDimensionStrategy "products", "template"
    }

    lint {
        abortOnError = false
        disable += ["MissingTranslation", "UnusedResources"]
    }

    sourceSets {
        main {
            manifest.srcFile("AndroidManifest.xml")
            kotlin.directories.add("src")
            java.srcDirs("src")
            assets.setSrcDirs(["assets"])
            res.setSrcDirs(["res"])
        }
        debug.jniLibs.setSrcDirs(["../libs/debug"])
        release.jniLibs.setSrcDirs(["../libs/release"])
    }
}
