[package]
name = "crossbow-android"
version = "0.2.3"
edition.workspace = true
authors = ["DodoRare Team <support@dodorare.com>"]
description = "Cross-Platform build tools and toolkit for games"
repository = "https://github.com/dodorare/crossbow"
license = "MIT OR Apache-2.0"
keywords = ["crossbow", "android", "port"]
readme = "README.md"
include = ["src/", "java/app/"]

[dependencies]
thiserror = { workspace = true }
displaydoc = { workspace = true }
anyhow = { workspace = true }

rust-embed = { workspace = true, features = ["include-exclude"], optional = true }

jni = { workspace = true, optional = true }
ndk-context = { workspace = true, optional = true }
lazy_static = { workspace = true, optional = true }
async-channel = { workspace = true, optional = true }

[features]
default = ["android"]
android = ["jni", "ndk-context", "lazy_static", "async-channel"]
embed = ["rust-embed"]
