[package]
name = "crossbow-android"
version = "0.1.3"
edition = "2021"
authors = ["DodoRare Team <support@dodorare.com>"]
description = "Cross-Platform Rust Toolkit for Games 🏹"
repository = "https://github.com/dodorare/crossbow"
license = "Apache-2.0"
keywords = ["crossbow", "android", "port"]
readme = "README.md"

[dependencies]
jni = "0.19"

[package.metadata]
app_name = "crossbow_android"
target_sdk_version = 30
android_build_targets = ["aarch64-linux-android"]
