[package]
name = "crossbow-android"
version = "0.1.3"
edition = "2021"
authors = ["DodoRare Team <support@dodorare.com>"]
description = "Cross-Platform Rust Toolkit for Games 🏹"
repository = "https://github.com/dodorare/crossbow"
license = "Apache-2.0"
keywords = ["crossbow", "android", "port"]
readme = "README.md"

[dependencies]
thiserror = "1.0"
displaydoc = "0.2"
anyhow = "1.0"
jni = "0.19"
ndk-context = "0.1"
# ndk-glue = "0.6.2"
# ndk = "0.6"

[package.metadata]
app_name = "crossbow_android"
target_sdk_version = 30
android_build_targets = ["aarch64-linux-android"]
