[package]
name = "crossbundle"
version = "0.2.3"
edition.workspace = true
authors = ["DodoRare Team <support@dodorare.com>"]
description = "Build and publish apps for Android/iOS"
repository = "https://github.com/dodorare/crossbow"
license = "MIT OR Apache-2.0"
keywords = ["tool", "android", "ios"]
readme = "README.md"

[lib]
name = "crossbundle_lib"
path = "src/lib.rs"

[[bin]]
name = "crossbundle"
path = "src/main.rs"

[dependencies]
crossbow = { workspace = true, default-features = false, features = ["update-manifest"] }
crossbundle-tools = { workspace = true, default-features = false }
android-tools = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }
colored = { workspace = true }
displaydoc = { workspace = true }
pretty_env_logger = { workspace = true }
log = { workspace = true }

fs_extra = { workspace = true }
dunce = { workspace = true }
ureq = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["android", "apple"]
android = ["crossbow/android", "crossbundle-tools/android", "android-tools"]
apple = ["crossbow/ios", "crossbundle-tools/apple"]
