plugins {
    id "com.android.library"
}

apply from: "publish.gradle"

dependencies {
    implementation libraries.androidxCore
    // implementation "androidx.games:games-activity:1.1.0"
}

android {
    namespace = "com.crossbow.library"

    compileSdk = versions.compileSdk
    buildToolsVersion = versions.buildTools
    ndkVersion = versions.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(versions.javaVersion)
        targetCompatibility = JavaVersion.toVersion(versions.javaVersion)
    }

    defaultConfig {
        minSdk = versions.minSdk
        targetSdk = versions.targetSdk
        manifestPlaceholders = [crossbowLibraryVersion: versions.crossbowLibrary]
    }

    lint {
        abortOnError = false
        disable += ["MissingTranslation", "UnusedResources"]
    }

    sourceSets {
        main {
            manifest.srcFile("AndroidManifest.xml")
            kotlin.directories.add("src")
            assets.setSrcDirs(["assets"])
            res.setSrcDirs(["res"])
        }
        debug.jniLibs.setSrcDirs(["libs/debug"])
        release.jniLibs.setSrcDirs(["libs/release"])
    }
}
