buildscript {
    apply from: "app/config.gradle"
    repositories {
        google()
        mavenCentral()
        mavenCrossbowGithub()
    }
    dependencies {
        classpath libraries.androidGradlePlugin
    }
}

apply from: "app/config.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
