buildscript {
    apply from: "config.gradle"
    repositories {
        google()
        mavenCentral()
        mavenCrossbowGithub()
    }
    dependencies {
        classpath libraries.androidGradlePlugin
    }
}

apply plugin: "com.android.library"
apply from: "config.gradle"
apply from: "publish.gradle"

repositories {
    google()
    mavenCentral()
    mavenCrossbowGithub()
}

dependencies {
    implementation libraries.androidxAppcompat
    implementation "com.android.billingclient:billing:9.1.0"

    if (rootProject.findProject(":lib")) {
        implementation project(":lib")
    } else if (rootProject.findProject(":crossbow:lib")) {
        implementation project(":crossbow:lib")
    } else if(getCustomBuildMode()) {
        // Custom build mode. In this scenario this project is the only one around and the Crossbow
        // library is available through the pre-generated crossbow-lib.*.aar android archive files.
        debugImplementation fileTree(dir: "../libs/debug", include: ["*.jar", "*.aar"])
        releaseImplementation fileTree(dir: "../libs/release", include: ["*.jar", "*.aar"])
    } else {
        implementation libraries.crossbowLibrary
    }
}

android {
    namespace = "com.crossbow.play_billing"
    compileSdk = versions.compileSdk
    buildToolsVersion = versions.buildTools

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(versions.javaVersion)
        targetCompatibility = JavaVersion.toVersion(versions.javaVersion)
    }

    defaultConfig {
        minSdk = versions.minSdk
        targetSdk = versions.targetSdk

        missingDimensionStrategy "products", "template"
    }

    lint {
        abortOnError = false
        disable += ["MissingTranslation", "UnusedResources"]
    }

    sourceSets {
        main {
            manifest.srcFile("AndroidManifest.xml")
            kotlin.directories.add("src")
            assets.setSrcDirs(["assets"])
            res.setSrcDirs(["res"])
        }
    }
}
