name: Docker images
on:
  push:
    branches: [main, add-plugin-support]
    paths:
    - '.github/docker/*.Dockerfile'
    - '.github/workflows/docker.yml'
jobs:
  build-crossbundle-dockerfile:
    name: Build Crossbundle Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Crossbundle image
      run: docker build -t ghcr.io/dodorare/crossbundle -f .github/docker/crossbundle.Dockerfile .
    - name: Publish Crossbundle Docker Image
      env:
        DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $DOCKER_TOKEN | docker login ghcr.io -u enfipy --password-stdin
        docker push ghcr.io/dodorare/crossbundle
